apiVersion: v1
kind: PersistentVolume
metadata:
  name: todoapp-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /data/todoapp
  persistentVolumeReclaimPolicy: Retain
