apiVersion: v1
kind: Secret
metadata:
  name: todoapp-secret
  namespace: todoapp
type: Opaque
data:
  DB_HOST: "bXlzcWwtc2VydmljZQ=="
  DB_NAME: "YXBwX2Ri"
  DB_PASSWORD: "MTIzNA=="
  DB_USER: "YXBwX3VzZXI="
  SECRET_KEY: "Y2hhbmdlLW1l"
